config/routes.rb
Rails.application.routes.draw do
  resources :products

  resources :comments

  resources :authors

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	belongs_to :author

	scope :current, -> { where(current: true) }
	scope :retired, -> { where(current: false) }

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :articles, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  include ArticlesHelper

  def index
    @articles = Article.all
  end

  def show
    @comment = @article.comments.new
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :author_id)
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.all
  end

  def show
  end

  def new
    @author = Author.new
  end

  def edit
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author, notice: 'Author was successfully created.'
    else
      render :new
    end
  end

  def update
    if @author.update(author_params)
      redirect_to @author, notice: 'Author was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @author.destroy
    redirect_to authors_url, notice: 'Author was successfully destroyed.'
  end

  private
  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :email)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  def edit
  end

  def create
    @comment = Comment.create(comment_params)
    redirect_to @comment.article, notice: 'Comment was successfully created.'
  end

  def update
    @comment.update(comment_params)
    redirect_to @comment.article, notice: 'Comment was successfully updated.'
  end

  def destroy
    @article = @comment.article
    @comment.destroy
    redirect_to @article, notice: 'Comment was successfully destroyed.'
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:article_id, :body)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @products = Product.all
    flash[:notice] = "omg a new div"
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Below are examples of helper methods available views.
	# To be available in controllers, you must write

	#           include ApplicationHelper   
	
	# in controller

	def current_user
		@current_user ||= User.find_by_id(session[:user])
	end

	def logged_in?
		current_user != nil
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	# Example of custom helper method to style link
	def styled_link_to_article(article)
    css_class = "current" if article.current?
    link_to(article.title, article, class: css_class)
	end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.number_field :author_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<% @articles.each do |article| %> <!-- Database query --> 
  <div>
    <%= styled_link_to_article(article) %>
  </div>
<% end %>

<br>

<div>
  <%= link_to 'New Article', new_article_path %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= link_to 'Back', articles_path %>

<h1><%= @article.title %></h1>
<p>By <%= link_to @article.author.name, @article.author %></p>
<div class="article content">
	<p><%= @article.body %></p>
	<%= link_to 'Edit', edit_article_path(@article) %> 
	<%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

<!-- 1. Fix the database query in view. This will blow up unless we account for the unsaved comment -->
<!-- 4. (Back to keynote). Change the code below to render a partial for a collection -->

<%= render partial: @article.comments %>

<!-- 2. Change the code below to render a partial for the comment form; send a local variable for comment -->
<!-- 3. (Back to keynote) Then, make it accessible as a shared partial -->

<%= render partial: 'shared/comment_form', locals: { comment: @comment } %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

app/views/comments/_comment.html.erb
<% unless comment.new_record? %>
	<div class="comment content">
		<%= comment.body %>
		<%= link_to 'Edit', edit_comment_path(comment) %> 
		<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= f.text_area :body, placeholder: "type your comment here" %><br>
  <%= f.hidden_field :article_id%>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BetterViews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.image %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Rails Helper Method Examples</h1>
<h3>DISCLAIMER: The purpose of this page is to show many types of Rails helpers at the same time (not necessarily good code) </h3>

<hr>

<p>
  <strong>pluralize(@products.count, 'product')</strong>
  <%= pluralize(@products.count, 'product') %>
</p>

<hr>

<p>
  <strong>image_tag @product.image:</strong>
  <%= image_tag @product.image %>
</p>

<hr>

<p>
  <strong>time_ago_in_words(@product.created_at):</strong>
  <%= time_ago_in_words(@product.created_at) %>
</p>

<hr>

<p>
  <strong>number_to_currency(@product.price / 100.00)</strong>
  <%= number_to_currency(@product.price / 100.00) %>
</p>

<hr>

<p>
  <strong>number_to_percentage(42, precision: 1)</strong>
  <%= number_to_percentage(42, precision: 1) %>
</p>

<hr>

<p> 
  <strong>date_select :product, :updated_at</strong>
  <%= date_select :product, :updated_at %> <br>
  <strong>check_box("post", "validated")</strong>
  <%= check_box("post", "validated") %> <br>
  <strong>password_field_tag :some_attribute</strong>
  <%= password_field_tag :some_attribute %> <br>
  <strong>select_tag 'product', options_from_collection_for_select(@products, 'id', 'name')</strong>
  <%= form_tag products_path do %>
    <%= select_tag 'product', options_from_collection_for_select(@products, 'id', 'name') %>
  <% end %>
</p>

<hr>

<table>
  <strong>cycle</strong>
 <% @products.each do |product| %>
   <tr class="<%= cycle('odd', 'even') %>">
     <td><%= product.name %></td>
   </tr>
 <% end %>
</table>

<hr>

<p>
  <strong>button_to "Broken Button. Don't click me!", products_path </strong>
  <%= button_to "Broken Button. Don't click me!", products_path %>
</p>

<hr>

<p>
  <strong>link_to 'Index', products_path</strong> <br>
  <%= link_to 'Index', products_path %>
</p>

<hr>

<p>
  <strong>flash.each do |name, msg| <br>
  content_tag :div, msg, :id => "flash_#{name}" <br>
end </strong>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash-#{name}" %>
<% end %>
</p>

app/views/shared/_comment_form.html.erb
<%= form_for(comment) do |f| %>
  <%= f.text_area :body, placeholder: "type your comment here" %><br>
  <%= f.hidden_field :article_id%>
  <%= f.submit %>
<% end %>